<a href="https://colab.research.google.com/github/Thanmai09-gif/ki/blob/main/heart_disease_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Data Collection and Processing

In [ ]:
#loading the csv data to pandas df
heart_data = pd.read_csv('//content/heart.csv')

In [ ]:
#print frist 5 rows
heart_data.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   52    1   0       125   212    0  ...      0      1.0      2   2     3       0
1   53    1   0       140   203    1  ...      1      3.1      0   0     3       0
2   70    1   0       145   174    0  ...      1      2.6      0   0     3       0
3   61    1   0       148   203    0  ...      0      0.0      2   1     3       0
4   62    0   0       138   294    1  ...      0      1.9      1   3     2       0

[5 rows x 14 columns]

In [ ]:
#print last 5 rows
heart_data.tail()

      age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca  thal  target
1020   59    1   1       140   221  ...      0.0      2   0     2       1
1021   60    1   0       125   258  ...      2.8      1   1     3       0
1022   47    1   0       110   275  ...      1.0      1   1     2       0
1023   50    0   0       110   254  ...      0.0      2   0     2       1
1024   54    1   0       120   188  ...      1.4      1   1     3       0

[5 rows x 14 columns]

In [ ]:
#number of rows and columns in the dataset
heart_data.shape

(1025, 14)

In [ ]:
#getting some information about the dataset
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [ ]:
#checking for missing values
heart_data.isnull()

        age    sex     cp  trestbps  ...  slope     ca   thal  target
0     False  False  False     False  ...  False  False  False   False
1     False  False  False     False  ...  False  False  False   False
2     False  False  False     False  ...  False  False  False   False
3     False  False  False     False  ...  False  False  False   False
4     False  False  False     False  ...  False  False  False   False
...     ...    ...    ...       ...  ...    ...    ...    ...     ...
1020  False  False  False     False  ...  False  False  False   False
1021  False  False  False     False  ...  False  False  False   False
1022  False  False  False     False  ...  False  False  False   False
1023  False  False  False     False  ...  False  False  False   False
1024  False  False  False     False  ...  False  False  False   False

[1025 rows x 14 columns]

In [ ]:
#handling missing values
df=pd.read_csv("heart.csv")
df.dropna()

      age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca  thal  target
0      52    1   0       125   212  ...      1.0      2   2     3       0
1      53    1   0       140   203  ...      3.1      0   0     3       0
2      70    1   0       145   174  ...      2.6      0   0     3       0
3      61    1   0       148   203  ...      0.0      2   1     3       0
4      62    0   0       138   294  ...      1.9      1   3     2       0
...   ...  ...  ..       ...   ...  ...      ...    ...  ..   ...     ...
1020   59    1   1       140   221  ...      0.0      2   0     2       1
1021   60    1   0       125   258  ...      2.8      1   1     3       0
1022   47    1   0       110   275  ...      1.0      1   1     2       0
1023   50    0   0       110   254  ...      0.0      2   0     2       1
1024   54    1   0       120   188  ...      1.4      1   1     3       0

[1025 rows x 14 columns]

In [ ]:
#checking for missing values
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
#statistical measures about the data
heart_data.describe()

               age          sex  ...         thal       target
count  1025.000000  1025.000000  ...  1025.000000  1025.000000
mean     54.434146     0.695610  ...     2.323902     0.513171
std       9.072290     0.460373  ...     0.620660     0.500070
min      29.000000     0.000000  ...     0.000000     0.000000
25%      48.000000     0.000000  ...     2.000000     0.000000
50%      56.000000     1.000000  ...     2.000000     1.000000
75%      61.000000     1.000000  ...     3.000000     1.000000
max      77.000000     1.000000  ...     3.000000     1.000000

[8 rows x 14 columns]

In [ ]:
#checking the distribution of target variable
heart_data['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

1 represents **Defective heart**

0 represents **Healthy heart**

In [ ]:
#splitting the features and target
X = heart_data.drop(columns='target',axis=1)
Y = heart_data['target']

In [ ]:
print(X)

      age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0      52    1   0       125   212  ...      0      1.0      2   2     3
1      53    1   0       140   203  ...      1      3.1      0   0     3
2      70    1   0       145   174  ...      1      2.6      0   0     3
3      61    1   0       148   203  ...      0      0.0      2   1     3
4      62    0   0       138   294  ...      0      1.9      1   3     2
...   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
1020   59    1   1       140   221  ...      1      0.0      2   0     2
1021   60    1   0       125   258  ...      1      2.8      1   1     3
1022   47    1   0       110   275  ...      1      1.0      1   1     2
1023   50    0   0       110   254  ...      0      0.0      2   0     2
1024   54    1   0       120   188  ...      0      1.4      1   1     3

[1025 rows x 13 columns]

In [ ]:
print(Y)

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

Splitting the data into Training data and Testing data using train_test_split

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape,X_test.shape)

(1025, 13) (820, 13) (205, 13)

Model Training

Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
#training the logistic regression model with Training data
model.fit(X_train,Y_train)

NameError: name 'model' is not defined

Model Evaluation

Accuracy Score

In [ ]:
#accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [ ]:
print("Accuracy on Training data : ", training_data_accuracy)

Accuracy on Training data :  0.8524390243902439

In [ ]:
#accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [ ]:
print("Accuracy on Test data : ", test_data_accuracy)

Accuracy on Test data :  0.8048780487804879

Building a Predictive System

In [ ]:
import numpy as np
import pandas as pd

input_data = (51,0,2,140,308,0,0,142,0,1.5,2,1,2)
#change the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

#reshape the numpu array as we are predicting for only one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# Convert the numpy array back to a DataFrame with feature names
# This ensures consistency with the training data X_train
input_data_df = pd.DataFrame(input_data_reshaped, columns=X_train.columns)

prediction = model.predict(input_data_df)
print(prediction)

if(prediction[0] == 0):
  print("The Person does not have a Heart Disease")

else:
  print("The Person has Heart Disease")

NameError: name 'X_train_prediction' is not defined

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# --- Data Collection and Processing (Re-defining X_train and model) ---

# loading the csv data to pandas df
heart_data = pd.read_csv('heart.csv')

# splitting the features and target
X = heart_data.drop(columns='target',axis=1)
Y = heart_data['target']

# Splitting the data into Training data and Testing data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

# --- Model Training (Re-training the model) ---

# Logistic Regression Model
model = LogisticRegression()

# training the logistic regression model with Training data
model.fit(X_train, Y_train)

# --- Building a Predictive System ---

input_data = (51,0,2,140,308,0,0,142,0,1.5,2,1,2)

# change the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array as we are predicting for only one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# Convert the numpy array back to a DataFrame with feature names
# This ensures consistency with the training data X_train
input_data_df = pd.DataFrame(input_data_reshaped, columns=X_train.columns)

prediction = model.predict(input_data_df)
print(prediction)

if(prediction[0] == 0):
  print("The Person does not have a Heart Disease")

else:
  print("The Person has Heart Disease")

FileNotFoundError: [Errno 2] No such file or directory: 'heart.csv'